env:
  global:
    - CC_TEST_REPORTER_ID=6901f64ef53effa16b51755b09c5a82cd063a88786f2bc365e74524b2e95d21b
language: node_js
node_js:
  - "14"
  - "12"
  - "10"
sudo: false
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run lint
  - npm run coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
